### ISSUE TITLE
Enable Appveyor tests

### ISSUE THREAD

**Issue by AStupidBear** [chriselrod/LoopVectorization.jl#112]

**Comment by chriselrod** [comment]
Do you need x86, or is x64 on the latest Julia release (i.e., currently 1.4) and nightly good enough?

If you need x64, that'll take some effort to fix the bugs. It looked like most of them are in SLEEFPirates.jl.

**Comment by AStupidBear** [comment]
I request Appveyor because `SLEEFPrirates.log` only failed on x86. See https://ci.appveyor.com/project/one-more-minute/nnlib-jl/builds/32769665. I don't have a x86 machine therefore not able to debug this.

**Comment by chriselrod** [comment]
Okay. I think that if I download a [32-bit binary](https://julialang.org/downloads/) that I should be able to test it locally on a 64-bit system to debug it.

**Comment by AStupidBear** [comment]
>Okay. I think that if I download a [32-bit binary](https://julialang.org/downloads/) that I should be able to test it locally on a 64-bit system to debug it. ...

@chriselrod That's reported in SLEEFPirates. Not a LoopVec issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chriselrod** [comment]
Okay, now [testing on x86](https://ci.appveyor.com/project/chriselrod/loopvectorization-jl). Are the latest-release and nightly good enough?

On Travis, I'm testing 1.1, latest-release, and nightly.

**Comment by AStupidBear** [comment]
Good enough. Thanks!
