### ISSUE TITLE
vreduce cannot handle Vector input when using dims argument

### ISSUE THREAD

**Issue by AStupidBear** [chriselrod/LoopVectorization.jl#125]
```julia
julia> vreduce(+, [1,2,3], dims = 1)
ERROR: BoundsError: attempt to access 0-element Array{Symbol,1} at index [1]
```

This error affects calling `softmax([0.5, 0.5]`.

**Comment by chriselrod** [comment]
I added a simple fix.
The underlying problem -- handling stored reductions that don't actually have any associated loops -- would be a little more complicated. So I'm adding this simple fix for now.

**Comment by AStupidBear** [comment]
Thanks!
