### ISSUE TITLE
Consider replacing \ast with a different symbol

### ISSUE THREAD

**Issue by MasonProtter** [chriselrod/LoopVectorization.jl#13]
Currently `∗` (`\ast`) is a lazy multiplication operator, but in many fonts the difference between it and `*` is not readily apparent unless they are side by side. I'd reccomend using a unicode modifier on top of `*` instead. Perhaps `*̂` (`*\hat`).

**Comment by chriselrod** [comment]
In Cygwin, `*\hat` looks more like `*` than `\ast`. I'll have to get home before I can try a proper terminal emulator.

[Here](https://github.com/JuliaLang/julia/blob/master/src/julia-parser.scm#L29) are all the operators that have the same precedence as `*`. What about `\circledast`?

**Comment by MasonProtter** [comment]
Another option would be `*ˡ` (`*\^l`) where the idea is that the `ˡ` denotes lazy. Just in case a reader doesn't know, any of the operators in the link above can also be modified with unicode modifiers such as `\hat`, `\bar`, etc. or superscripts and subscripts to create yet another distinct infix operator with the precedence of times.

**Comment by chriselrod** [comment]
I like `*ˡ`.

Do you think I should ask on Discourse or somewhere for more feedback, or just go ahead and make the change?

**Comment by MasonProtter** [comment]
It won't hurt to ask for feedback, but I suspect that `\ast` isn't used in any serious code yet, so it probably doesn't matter much. If you do get rid of `\ast`, I'd save it for `v0.4.0` since it'd technically be a "breaking change". In the meantime, you can make `*ˡ` and set `\ast` as an alias for it.

**Comment by chriselrod** [comment]
I went ahead and replaced `\ast` with `*ˡ`, and then defined `\ast` as an alias. Once I release `v0.4.0`, I'll delete that single line.
