### ISSUE TITLE
Support for `log1p`

### ISSUE THREAD

**Issue by guyvdbroeck** [chriselrod/LoopVectorization.jl#152]
For the purpose of implementing `logsumexp` inside of an @avx loop, it would be nice to have `log1p` accounted for in https://github.com/chriselrod/LoopVectorization.jl/blob/master/src/costs.jl ?

**Comment by chriselrod** [comment]
I'll add it for LoopVectorization 0.9, which will hopefully be ready in the next month.
It will include changes that make this more important.

I'll also probably add a script that should be able to auto-generate the cost dict, in case
a) Someone doesn't want to use the defaults; maybe their architecture is significantly different.
b) It will be easier to update costs for additional special functions (like `log1p`), and update costs for old ones with updated definitions.

In the mean time, `log1p` will still work correctly.

**Comment by oscardssmith** [comment]
Should this be closed now?

**Comment by chriselrod** [comment]
I need to make real entries that also reflect the profitability of unrolling once I merge the vecunroll branch, but that's not really about `log1p` support in particular.
