### ISSUE TITLE
@avx fails after Pkg update

### ISSUE THREAD

**Issue by LaurentPlagne** [chriselrod/LoopVectorization.jl#166]
Hi, I have made an update (Julia 1.5.2) on my package and I get an error with `@avx` macro:
```
using LoopVectorization
@inline function smooth_line(nrm1,j,i1,sl,rl,ih2,denom)
    if nrm1 >= 0
        @avx for i=i1:2:nrm1
            sl[i,j]=denom*(rl[i,j]+ih2*(sl[i,j-1]+sl[i-1,j]+sl[i+1,j]+sl[i,j+1]))
        end
    else
        @fastmath @inbounds @simd for i=i1:2:nrm1
            sl[i,j]=denom*(rl[i,j]+ih2*(sl[i,j-1]+sl[i-1,j]+sl[i+1,j]+sl[i,j+1]))
        end
    end
end


n=128
nrm1=n-1

sl=rand(n,n),rl=rand(n,n)
ih2,denom=1.0,1.0
j=1
smooth_line(nrm1,j,i1,sl,rl,ih2,denom)
```
ERROR: KeyError: key :j not found

**Comment by chriselrod** [comment]
Thanks for the issue. I'll look at it soon.
```julia
@avx for i=i1:2:nrm1
```
I haven't fixed [this issue](https://github.com/chriselrod/LoopVectorization.jl/issues/132) yet, but I plan on fixing it when I rewrite LoopVectorization.

**Comment by LaurentPlagne** [comment]
Ach, I forgot that I already asked a similar question... sorry for the noise.
