### ISSUE TITLE
CI failing on master

### ISSUE THREAD

**Issue by DilumAluthge** [chriselrod/LoopVectorization.jl#176]
Looks like all jobs (Julia 1.5, Julia 1, and Julia nightly) are failing on LoopVectorization master.

**Comment by chriselrod** [comment]
I think CI should pass now.
The most recent failures were either a just-introduced bug (not prefixing a constant with `VectorizationBase.`), or mostly harmless: I tweaked the optimization decisions for non-AVX512 cpus, which resulted in failures, so tests checking what specific decision it was making failed. Those tests are largely there to alert me of changes, so I can double check if something looks wrong.

**Comment by chriselrod** [comment]
Tests passed.
