### ISSUE TITLE
Code coverage bug: only the first line of `@avx` counts as covered

### ISSUE THREAD

**Issue by DilumAluthge** [chriselrod/LoopVectorization.jl#178]
> a bug where only the first line of @avx for counts as tested when covered, and all the remaining lines count as uncovered.

> Probably a LoopVectorization issue, in that it should try and stick the LineNumberNodes from the original expression somewhere?

We've seen this in both Gaius.jl and PaddedMatrices.jl (https://github.com/chriselrod/PaddedMatrices.jl/issues/13).

**Comment by chriselrod** [comment]
Thanks for the issue.
I don't know how line numbers get recorded, so I'm not sure how to solve this.

One idea that might work would be to give each operation a field to hold a `LineNumberNode`, and give each operation the node from the expression above it, and then insert these into the final expression. This could also give slightly more informative error messages, which I think use these?
However, the code actually gets run inside a generated function, so I'm not sure that would work.

Another idea would be to collect the line number nodes, and dump them all in the macro output. Either way, I'm assuming the `LineNumberNode`s are key.

**Comment by DilumAluthge** [comment]
I think we might need some help with someone that knows more about how code coverage works.

Maybe @vtjnash can help with this?

**Comment by vtjnash** [comment]
It looks like `@avx` transforms it into a form that strips out the line number information for the cases you're testing, and also emits duplicate code with `LoopVectorization.check_args`, so you need to fix that, and should test both cases to provide complete coverage.
