### ISSUE TITLE
Does @avx allow for conditionals inside a loop?

### ISSUE THREAD

**Issue by prosoitos** [chriselrod/LoopVectorization.jl#204]
*Note: I am new to LoopVectorization, so I might be doing something wrong and this may not be an issue with the package.*

I would appreciate help with this.

While running the following:

```jl
using LoopVectorization

function slow(n::Int, digits::String)
    total = 0.0
    @avx for i in 1:n
        if !occursin(digits, string(i))
            total += 1.0 / i
        end
    end
    println("total = ", total)
end
```

I am getting:
> ERROR: LoadError: Don't know how to handle expression.
if !(occursin(digits, string(i)))
    #= REPL[22]:5 =#
    total = add_fast(total, Base.FastMath.div_fast(1.0, i))
end
Stacktrace:
 [1] push!(::LoopVectorization.LoopSet, ::Expr, ::Int64, ::Int64) at /home/marie/.julia/packages/LoopVectorization/8MeJu/src/graphs.jl:838                          
 [2] add_block!(::LoopVectorization.LoopSet, ::Expr, ::Int64, ::Int64) at /home/marie/.julia/packages/LoopVectorization/8MeJu/src/graphs.jl:481                          
 [3] add_loop!(::LoopVectorization.LoopSet, ::Expr, ::Int64) at /home/marie/.julia/packages/LoopVectorization/8MeJu/src/graphs.jl:620                          
 [4] copyto! at /home/marie/.julia/packages/LoopVectorization/8MeJu/src/constructors.jl:15 [inlined]                                                                                     
 [5] LoopVectorization.LoopSet(::Expr, ::Symbol) at /home/marie/.julia/packages/LoopVectorization/8MeJu/src/constructors.jl:67                     
 [6] LoopVectorization.LoopSet(::Expr, ::Module) at /home/marie/.julia/packages/LoopVectorization/8MeJu/src/constructors.jl:71                     
 [7] @avx(::LineNumberNode, ::Module, ::Any) at /home/marie/.julia/packages/LoopVectorization/8MeJu/src/constructors.jl:159                    
in expression starting at REPL[22]:3

Without the conditional, things work fine.

Thank you!

**Comment by chriselrod** [comment]
Currently only simple 1-line conditionals work, of the form:
```julia
function slow(n::Int, digits::String)
    total = 0.0
    @avx for i in 1:n
        total += !occursin(digits, string(i)) ? 1.0 / i : 0.0
    end
    total
end
```
Also, it won't give the correct answer here.
```julia
julia> string_and_print(x) = @show string(x)
string_and_print (generic function with 1 method)

julia> function wrong(n::Int, digits::String)
           total = 0.0
           @avx for i in 1:n
               total += !occursin(digits, string_and_print(i)) ? 1.0 / i : 0
           end
           total
       end
wrong (generic function with 1 method)

julia> function correct(n::Int, digits::String)
           total = 0.0
           for i in 1:n
               total += !occursin(digits, string_and_print(i)) ? 1.0 / i : 0
           end
           total
       end
correct (generic function with 1 method)

julia> wrong(4, "3")
string(x) = "VectorizationBase.MM{8, 1, Int64}<1, 2, 3, 4, 5, 6, 7, 8>"
0.0

julia> correct(4, "3")
string(x) = "1"
string(x) = "2"
string(x) = "3"
string(x) = "4"
1.75

julia> wrong(9, "3")
string(x) = "VectorizationBase.MM{8, 1, Int64}<1, 2, 3, 4, 5, 6, 7, 8>"
string(x) = "VectorizationBase.MM{8, 1, Int64}<9, 10, 11, 12, 13, 14, 15, 16>"
0.0

julia> correct(9, "3")
string(x) = "1"
string(x) = "2"
string(x) = "3"
string(x) = "4"
string(x) = "5"
string(x) = "6"
string(x) = "7"
string(x) = "8"
string(x) = "9"
2.4956349206349207
```
LoopVectorization works by using vector-instructions to perform multiple loop iterations at a time. So instead of 9 iterations where `i` goes from 1 to 9, it does 2 iterations, the first where i = 1,...,8, and then another where i = 9,...,16 (and then it ignores the answer for 10,...,16).

This happens to be slower here, because `string(::Int)` is much faster than `string(::MM)` (`MM` is the type of the vector of indices):
```julia
julia> @benchmark string(2)
BenchmarkTools.Trial:
  memory estimate:  96 bytes
  allocs estimate:  2
  --------------
  minimum time:     16.209 ns (0.00% GC)
  median time:      17.423 ns (0.00% GC)
  mean time:        22.348 ns (14.98% GC)
  maximum time:     2.031 μs (97.68% GC)
  --------------
  samples:          10000
  evals/sample:     998

julia> @benchmark string(LoopVectorization.MM{8}(2))
BenchmarkTools.Trial:
  memory estimate:  4.06 KiB
  allocs estimate:  71
  --------------
  minimum time:     7.635 μs (0.00% GC)
  median time:      7.939 μs (0.00% GC)
  mean time:        8.815 μs (2.66% GC)
  maximum time:     825.847 μs (96.74% GC)
  --------------
  samples:          10000
  evals/sample:     4

julia> LoopVectorization.MM{8}(1)
VectorizationBase.MM{8, 1, Int64}<1, 2, 3, 4, 5, 6, 7, 8>

julia> LoopVectorization.MM{4}(1)
VectorizationBase.MM{4, 1, Int64}<1, 2, 3, 4>
```

**Comment by prosoitos** [comment]
OK. Thank you very much for taking the time to give all these explanations! This is **very** useful.

I guess I will close this issue then 🙂
