### ISSUE TITLE
for loop with a negative step

### ISSUE THREAD

**Issue by christianpeel** [chriselrod/LoopVectorization.jl#21]
Thanks for all your work on this! 

It would be useful for some of my code to have a negative step size in the for loop.  I'd be happy if either `toy2!` or `toy3!` could be made to work.
```julia
using LoopVectorization

function toy1!(B,X,κ)
    n = size(B,1)
    @inbounds for i = κ-1:-1:1
        for nx=1:n
            B[nx,κ] -=X[i]*B[nx,i]
        end
    end
end
# the following function never exits lowering (?). Or doing
# something triggered by the @avx macro
function toy2!(B,X,κ)
    n = size(B,1)
    @avx for i = κ-1:-1:1
        for nx=1:n
            B[nx,κ] -=X[i]*B[nx,i]
        end
    end
end
# I'm willing to switch to this form of the same function
# which doesn't have the negative step, but it fails lowering with
# ERROR: LoadError: InexactError: trunc(Int64, Inf)
function toy3!(B,X,κ)
    n = size(B,1)
    @avx for ii = 1:κ-1
        i = κ-ii
        for nx=1:n
            B[nx,κ] -=X[i]*B[nx,i]
        end
    end
end

N = 4
X = randn(N);
B1 = randn(N, N);
B2 = copy(B1);
B3 = copy(B1);
toy1!(B1,X,3)
toy2!(B2,X,3) # hopefully this would be faster, if we could run it :-)
toy3!(B3,X,3) # hopefully this would be faster, if we could run it :-)
```

**Comment by chriselrod** [comment]
You could put `@avx` on just the inner loops.

But I'll work on this. At the very least, `toy3!` should be made to work.

However, in your toy examples...
```julia
julia> function toy0!(B,X,κ)
           n = size(B,1)
           @inbounds for i = 1:κ-1
               for nx=1:n
                   B[nx,κ] -=X[i]*B[nx,i]
               end
           end
       end
toy0! (generic function with 1 method)

julia> function toy1!(B,X,κ)
           n = size(B,1)
           @inbounds for i = κ-1:-1:1
               for nx=1:n
                   B[nx,κ] -=X[i]*B[nx,i]
               end
           end
       end
toy1! (generic function with 1 method)

julia> N = 4
4

julia> X = randn(N);

julia> B1 = randn(N, N);

julia> B0 = copy(B1);

julia> toy0!(B0, X, 3);

julia> toy1!(B1, X, 3);

julia> B0 ≈ B1
true
```
The order doesn't matter.

Presumably, in your real problem, the order you evaluate them does matter?
If so, could you provide a toy problem showing the way it matters?

The tempting solution here for toy2 would be to just evaluate the iterations in order. If that doesn't work, I'd like to see an example showing the restrictions.
`cumsum` type loops currently aren't supported (if they ever are, it'll be by not vectorizing so that it at least gives the correct answer). But some order restrictions are easier.

**Comment by christianpeel** [comment]
You're right!   I confess that I had not noticed that I could re-order the loops!  I'll look at this more tomorrow.

If you're curious, the function I'm trying to optimize is `l2U` at this [gist](https://gist.github.com/christianpeel/73d0a68c9c1419d343390f389e12ef84).  There's code in `test.jl` at the end of the gist which shows that a version which uses your `@avx` macro (`l2AVX`) is indeed faster!  I'll try to get a version of this code into a branch of [LLLplus](https://github.com/christianpeel/LLLplus.jl) over the weekend or on Monday.

**Comment by christianpeel** [comment]
It took me three weeks instead of a weekend, yet I put the `l2` function that I was trying to optimize into [LLLplus](https://github.com/christianpeel/LLLplus.jl/tree/v1.2.5). The `lll` function in the same package is another function I would love to use `@avx` on.

I think you've done enough on this issue; I'll close it and open other issues as needed when I get back to using LoopVectorization.  Thanks!
