### ISSUE TITLE
Support ranges

### ISSUE THREAD

**Issue by MasonProtter** [chriselrod/LoopVectorization.jl#23]
```julia
using LoopVectorization
function f(a)
    s = 0.0
    @avx for i in eachindex(a)
        s += a[i]
    end
    s
end

julia> f([1,2,3]) 
6.0

julia> f(1:3)
 StackOverflowError:
 Stacktrace:
  [1] stridedpointer(::UnitRange{Int64}) at /Users/mason/.julia/packages/VectorizationBase/yJngh/src/vectorizable.jl:389 (repeats 80000 times)
```
I think this should be supportable. One (dumb) way to make this work would just be 
```julia
VectorizationBase.stridedpointer(r::AbstractRange) = VectorizationBase.stridedpointer(collect(r))
```
but I wonder if there's a way we can do it that doesn't require explicitly materializing the range. Maybe this issue should be moved to VectorizationBase though,

**Comment by chriselrod** [comment]
I fixed it without needing to create temporaries via, in VectorizationBase:
```julia
@inline stridedpointer(x::AbstractRange) = x
@inline load(r::AbstractRange, i::Tuple{<:Integer}) = @inbounds r[i[1] + 1]
```
and in SIMDPirates:
```julia
@inline vload(r::AbstractRange{T}, i::Tuple{_MM{W}}) where {W,T} = vmuladd(svrange(Val{W}(), T), step(r), @inbounds r[i[1].i + 1])
@inline vload(r::UnitRange{T}, i::Tuple{_MM{W}}) where {W,T} = vadd(svrange(Val{W}(), T), @inbounds r[i[1].i + 1])

@inline vload(r::AbstractRange{T}, i::Tuple{_MM{W}}) where {W,T} = vmuladd(svrange(Val{W}(), T), step(r), @inbounds r[i[1].i + 1])
@inline vload(r::UnitRange{T}, i::Tuple{_MM{W}}) where {W,T} = vadd(svrange(Val{W}(), T), @inbounds r[i[1].i + 1])
```
I haven't commited these changes yet, but will within the next few hours.

This is much slower than not having `@avx`, since it prevents LLVM's O(1) optimization of the loop.
Would be neat if we could avoid preventing that optimization.

**Comment by MasonProtter** [comment]
I have a use-case in mind that wouldn't benefit from `O(1)` optimization so I don't mind.

**Comment by chriselrod** [comment]
I'm closing this because I've now tagged a release where this works.
```julia
julia> f([1,2,3])
6.0

julia> f(1:3)
6.0
```

Let me know if you have any more problems.
