### ISSUE TITLE
`@avx unroll=3` does not work as intended

### ISSUE THREAD

**Issue by hofmannmartin** [chriselrod/LoopVectorization.jl#28]
I was experimenting with the loop unroll and stumbled upon a bug. The result of a calculation should be the same regardless of the `unroll` factor:
```julia
function test_avx2(x::Vector{T}, y::Vector{T}) where {T<:AbstractFloat}
    z = zero(T)
    @avx unroll=2 for i ∈ 1:length(x)
        z += x[i]*y[i]
    end
    return z
end

function test_avx3(x::Vector{T}, y::Vector{T}) where {T<:AbstractFloat}
    z = zero(T)
    @avx unroll=3 for i ∈ 1:length(x)
        z += x[i]*y[i]
    end
    return z
end

# test
T = Float32
N = 1024
x = rand(T,N)
y = rand(T,N)
@test test_avx2(x, y) ≈ test_avx3(x, y)
```
```
Test Failed at In[34]:24
  Expression: test_avx2(x, y) ≈ test_avx3(x, y)
   Evaluated: 258.05835f0 ≈ 172.16222f0

There was an error during testing
```
Closer inspection of the source code reveals that while `@code_native debuginfo=:none test_avx2(x, y)` gives me the expected unrolling in the main loop.
```
L32:
	vmovups	(%rcx,%rdx,4), %ymm2
	vmovups	32(%rcx,%rdx,4), %ymm3
	vfmadd231ps	(%rax,%rdx,4), %ymm2, %ymm0
	vfmadd231ps	32(%rax,%rdx,4), %ymm3, %ymm1
	addq	$16, %rdx
	cmpq	%rsi, %rdx
	jl	L32
```
This does not hold true for `test_avx3` which yields the same code snippet as `test_avx2`.

**Comment by chriselrod** [comment]
Thanks for the report.
I fixed the bug, and [added these to the tests](https://github.com/chriselrod/LoopVectorization.jl/blob/master/test/runtests.jl#L488) for LoopVectorization 0.4.0.
