### ISSUE TITLE
doc links in README is not working

### ISSUE THREAD

**Issue by dmolina** [chriselrod/LoopVectorization.jl#4]
Thanks a lot for your package, it is seem very nice!

I write you because when I want to study one package, I like to read the documentation. The links in the README.md to the docs is not working. 

Also, it should be nice of part of the examples and documentations in [Discourse forum](https://discourse.julialang.org/t/ann-loopvectorization/32843) not only should be in the documentation, but also a short version could be added to README.md.

**Comment by chriselrod** [comment]
I agree.
I should update and improve the README, and really need to add documentation.

**Comment by chriselrod** [comment]
The docs-latest link now works.

**Comment by chriselrod** [comment]
Links have been working for a while now.
