### ISSUE TITLE
Simple vmap throws error

### ISSUE THREAD

**Issue by baggepinnen** [chriselrod/LoopVectorization.jl#57]
`vmap!` has suddenly stopped working for me

```julia
julia> vmap!(sin, zeros(4), zeros(4))
ERROR: UndefVarError: vectorizable not defined
Stacktrace:
 [1] macro expansion at /home/fredrikb/.julia/packages/LoopVectorization/T2QRW/src/map.jl:25 [inlined]
 [2] vmap!(::typeof(sin), ::Array{Float64,1}, ::Array{Float64,1}) at /home/fredrikb/.julia/packages/LoopVectorization/T2QRW/src/map.jl:25
 [3] top-level scope at none:0

(v1.3) pkg> st LoopVectorization
    Status `~/.julia/environments/v1.3/Project.toml`
  [bdcacae8] LoopVectorization v0.6.12
  [d96e819e] Parameters v0.12.0
  [476501e8] SLEEFPirates v0.3.6
```

On PkgEval (julia 1.5), the error is also there but different
https://github.com/JuliaCI/NanosoldierReports/blob/7e2afe28cfedbd45fcaec2baf2343ca04ce64a5b/pkgeval/by_date/2020-02/20/logs/LowLevelParticleFilters/1.5.0-DEV-6a9a92683d.log#L222

**Comment by baggepinnen** [comment]
I had to do the following to get it to work
```julia
(v1.3) pkg> add VectorizationBase@0.2.5
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `~/.julia/environments/v1.3/Project.toml`
  [3d5dd08c] + VectorizationBase v0.2.5
  Updating `~/.julia/environments/v1.3/Manifest.toml`
  [21efa798] ↓ SIMDPirates v0.3.15 ⇒ v0.3.9
  [3d5dd08c] ↓ VectorizationBase v0.3.1 ⇒ v0.2.5
```

**Comment by chriselrod** [comment]
Hi, thanks for the report.
I [updated LoopVectorization](https://github.com/chriselrod/LoopVectorization.jl/commit/45cbcdc6da6f0d0e8d1f9b9845481682643291d4#diff-b07bff3453f82424d4b3d22ffabd686aR5) a few days ago to reflect that change, but while I increased VectorizationBase's version to 0.4.0 to reflect that change, I made the mistake of having [too open an upper bound](https://github.com/chriselrod/LoopVectorization.jl/blob/33f9cf807163e0b7dc1ef03fd62d4b748ce147af/Project.toml#L17) and also did not tag a new version of LoopVectorization with that update, meaning the package manager could break people's code.

I'll release a new version of LoopVectorization soon. I'm rerunning benchmarks now. Once those finished, assuming I don't see any regressions, I'll tag new versions (one after the other) of SIMDPirates, SLEEFPirates, and then LoopVectorization with updated compat bounds and Manifest files.

**Comment by chriselrod** [comment]
I was using relatively open bounds because of the following issue:
https://github.com/chriselrod/SLEEFPirates.jl/issues/1
Using open bounds did not actually address it, but I mistakenly thought it helped and didn't notice because of the stochastic nature of the package server falling out of sync with the general registry. The issue seems to have been resolved:
https://github.com/JuliaLang/Pkg.jl/issues/1694#issuecomment-590106680
By being strict on the compats, problems like this should not come up again.

But please let me know if you run into any more issues.
