### ISSUE TITLE
Broken rendering in the README?

### ISSUE THREAD

**Issue by ViralBShah** [chriselrod/LoopVectorization.jl#62]
I am using the latest chrome on mac.

![Screen Shot 2020-02-29 at 7 57 00 AM](https://user-images.githubusercontent.com/744411/75607857-1fffb700-5ac9-11ea-9c75-2d09f250b212.png)

**Comment by chriselrod** [comment]
Thanks for reporting this. What's odd is that the `\bfA`, `\bfB`, and `\bfC` show up correctly as the function arguments, but not inside the body of the function. `\_m` and `\_n` don't show up correctly either.

How does the `*\^l` look in the broadcasting section?
If that doesn't render well on Macs, do you have any other suggestions for a lazy-(matrix-)multiplication (that allows fusing with broadcasts) operator?

**Comment by DilumAluthge** [comment]
FWIW, I was able to get `\_m` and `\_n` working on Mac (both Firefox and Chrome) by installing the DejaVu Sans Mono fonts.
