### ISSUE TITLE
failed broadcasted vectorization

### ISSUE THREAD

**Issue by jebej** [chriselrod/LoopVectorization.jl#9]
With a vector `a=rand(1000)`, this works:
```
julia> @avx @. sin(a) + sqrt(a);
```
but this doesn't:
```
julia> @avx @. 3*a + sin(a) + sqrt(a);
ERROR: MethodError: no method matching add_broadcast!(::LoopVectorization.LoopSet, ::Symbol, ::Symbol, ::Array{Symbol,1}, ::Type{Int64})
```

**Comment by jebej** [comment]
If we replace the number `3` by a 1D array `[3.0]`, the code runs but the answer is wrong (I am assuming because it is reading out of bounds).
Transposing the vector by doing `[3.0]'` ends up working properly.

**Comment by JonasIsensee** [comment]
I can confirm.
There seem to be methods missing needed to work with scalars.
I had a brief look at the source code but couldn't figure out how to add that right away.

**Comment by chriselrod** [comment]
Thanks for the report. That's definitely an oversight.
I haven't tested it yet, but think this should work:
https://github.com/chriselrod/LoopVectorization.jl/blob/decouplevecunroll/src/broadcast.jl#L130
I'll add tests for this.

I'm (in that branch) currently in the middle of a lot of other changes. It should only only be another few hours.

**Comment by chriselrod** [comment]
Thanks for the report!
I added it as a test, and tests pass on 0.2.2.
https://github.com/chriselrod/LoopVectorization.jl/blob/master/test/runtests.jl#L440
